name: Node.js CI

on: push

jobs:
  umbreld:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/umbreld
    strategy:
      fail-fast: false
      matrix:
        task:
          - format:check
          # - lint
          - typecheck
          - test:unit -- --coverage --watch=false
          - test:integration -- --coverage --watch=false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # This is needed for the samba integration tests
      - name: Setup umbrel user
        run: |
          sudo adduser --gecos "" --disabled-password umbrel
          echo "umbrel:umbrel" | sudo chpasswd
          sudo usermod -aG sudo umbrel
      - name: Install dependencies
        run: |
          curl -s https://kopia.io/signing-key | sudo gpg --dearmor -o /etc/apt/keyrings/kopia-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/kopia-keyring.gpg] http://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
          sudo apt-get update
          sudo apt-get install -y unar imagemagick ffmpeg samba wsdd2 kopia bindfs cifs-utils smbclient
          sudo systemctl disable smbd wsdd2
          sudo npm clean-install
      - run: sudo npm run ${{ matrix.task }}
  ui:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/ui
    strategy:
      fail-fast: false
      matrix:
        task:
          - lint
          - format:check
          - typecheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install Umbreld dependencies
        if: ${{ matrix.task == 'typecheck' }}
        run: npm --prefix ../umbreld clean-install
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run ${{ matrix.task }}
